using device: cuda
Traceback (most recent call last):
  File "/home/liwentao/Dec-Tuning-in-Mat/baseline1/bert_ner_raw.py", line 88, in <module>
    train_X, train_y, val_X, val_y, test_X, test_y = ner_datasets.get_ner_data(dataset_name,args.shot,args.seed, fold=fold_num, norm=to_normalize)
  File "/home/liwentao/Dec-Tuning-in-Mat/baseline1/ner_datasets.py", line 134, in get_ner_data
    data =  get_matscholar_data(shot,seed)
  File "/home/liwentao/Dec-Tuning-in-Mat/baseline1/ner_datasets.py", line 121, in get_matscholar_data
    train_X, train_y = parse_file(os.path.join(data_dir, "{}shot/{}.txt".format(shot,seed)))
  File "/home/liwentao/Dec-Tuning-in-Mat/baseline1/ner_datasets.py", line 95, in parse_file
    f = open(f_name, 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/matsciner/1shot/3.txt'
using device: cuda
Traceback (most recent call last):
  File "/home/liwentao/Dec-Tuning-in-Mat/baseline1/bert_ner_raw.py", line 78, in <module>
    cache_dir = ensure_dir(args.cache_dir) if args.cache_dir else None
  File "/home/liwentao/Dec-Tuning-in-Mat/baseline1/bert_ner_raw.py", line 41, in ensure_dir
    Path(dir_path).mkdir(parents=True, exist_ok=True)
  File "/home/liwentao/miniconda3/envs/py38/lib/python3.8/pathlib.py", line 1288, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '../.cache'
using device: cuda
Traceback (most recent call last):
  File "/home/liwentao/Dec-Tuning-in-Mat/baseline1/bert_ner_raw.py", line 78, in <module>
    cache_dir = ensure_dir(args.cache_dir) if args.cache_dir else None
  File "/home/liwentao/Dec-Tuning-in-Mat/baseline1/bert_ner_raw.py", line 41, in ensure_dir
    Path(dir_path).mkdir(parents=True, exist_ok=True)
  File "/home/liwentao/miniconda3/envs/py38/lib/python3.8/pathlib.py", line 1288, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '../.cache'
using device: cuda
Traceback (most recent call last):
  File "/home/liwentao/Dec-Tuning-in-Mat/baseline1/bert_ner_raw.py", line 78, in <module>
    cache_dir = ensure_dir(args.cache_dir) if args.cache_dir else None
  File "/home/liwentao/Dec-Tuning-in-Mat/baseline1/bert_ner_raw.py", line 41, in ensure_dir
    Path(dir_path).mkdir(parents=True, exist_ok=True)
  File "/home/liwentao/miniconda3/envs/py38/lib/python3.8/pathlib.py", line 1288, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '../.cache'
